name: Homes
version: 0.1.0
author: Archer
main: Main
permission-message: &noperms "§cError: §fNo permission!"
commands:
  test:
    description: A test
    usage: /test
  home:
    description: Teleports the id to his home if set
    usage: /home <arg1> <arg2>
  sethome:
    description: Sets the id's home if location is valid
    usage: /sethome
    aliases: [homeset]
    permission: homes.set
permissions:
  homes.*:
    description: Grants access to ALL Homes commands
    children:
      homes.tp.self: true
      homes.tp.other: true
      homes.set: true
      homes.invite: true
      homes.admin: true
  homes.player:
    description: Grants access to all commands intended for players
    children:
      homes.tp.self: true
      homes.tp.other: true
      homes.set: true
      homes.invite: true
  homes.tp.self:
    description: Allows teleporting to own home.
    default: true
  homes.tp.other:
    description: Allows teleporting to other's homes.
    default: true
  homes.set:
    description: Allows setting location of home.
    default: true
  homes.invite:
    description: Allows invitation and uninvitation of other players.
    default: true
  homes.admin:
    description: Grants access to all administrative commands.
    default: op